[package]
name = "vaelixos"
version = "0.1.0"
edition = "2021"

[dependencies]
vaelix_core = { path = "src/kernel" }
sha2 = "0.10"
log = "0.4"
env_logger = "0.10"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
